### ISSUE TITLE
Could you provide alternative link for feature data

### ISSUE THREAD

**Issue by jinotter3** [zeroQiaoba/MERTools#4]
Hello, I am deeply interested in your work. Great paper and code base. 

But, since I live outside china, It is not possible for me to create Baidu account(I need chinese phone number for that), so I cannot access your feature files. 

Could you please provide an alternative link(e.g. Google Drive..) for feature data? It will be a huge help for me and others not living in china. Thanks.

**Comment by zeroQiaoba** [comment]
Thank you very much for your interest in our work. We provide another link for pre-extracted features.
```
https://terabox.com/s/1MBgt9JAUnrw-6581_nyYLw
```

**Comment by jinotter3** [comment]
Thank you for a quick response. It will be a great help.
