### ISSUE TITLE
The WeChat group cannot be joined

### ISSUE THREAD

**Issue by Cb1ock** [zeroQiaoba/MERTools#5]
The WeChat group mentioned here— https://mp.weixin.qq.com/s/70ruqPU8Hk3CgzPoiVQs6w —has reached its limit of 200 members and is currently not joinable by QR code. Could you please invite us to join it?

**Comment by zeroQiaoba** [comment]
Thanks very much for letting me know about this condition. We have created another WeChat group. 
![微信图片_20240507000538](https://github.com/zeroQiaoba/MERTools/assets/19849763/9790223f-f1c4-4a0e-89b5-5cea7d8657d5)

**Comment by zsxzs** [comment]
今年的微信群有吗？

**Comment by zeroQiaoba** [comment]
有的，您可以通过朋友邀请。或者发送邮件到官方邮箱申请加入 merchallenge.contact@gmail.com
