### ISSUE TITLE
ferplus读取经过openface处理的人脸图片有问题

### ISSUE THREAD

**Issue by speeds233** [zeroQiaoba/MERTools#7]
源代码是PATH_TO_RAW_FACE = {
	'MER2023': os.path.join(DATA_DIR['MER2023'], 'openface_face'),
}
但是openface_face是在features目录下，修改路径为
PATH_TO_RAW_FACE = {
	'MER2023': os.path.join(DATA_DIR['MER2023'], ‘features'，openface_face')
}后仍不能读取，因为openface_face目录里是一些目录，而图片在这些目录下，修改代码为读取该目录下图片时，又报错说代码是要读取视频，改路径为视频路径时又说代码只能读取图片。
希望作者能为我解惑，谢谢

**Comment by zeroQiaoba** [comment]
很感谢您对我们工作的关注。

在./MER2023 folder下，我们提供的openface代码提取的是人脸帧；visual feature extractor也是从人脸帧中提取的。

但是人脸帧文件比较多，传输比较费时。因此，在./MER2024和./MERBench下，我们提取的是人脸帧压缩后存下来的npy文件。visual feature extractor也是从npy文件中提取的。

因此，两者需要匹配。最好用一个文件夹下的face extraction and visual feature extractor代码。

此外，数据具体存储路径为：
./mer2023-dataset-process/openface_face/sample_00000008/sample_00000008.npy

**Comment by speeds233** [comment]
谢谢您的回答，代码已跑通
